<header>
    <nav class="search">
        <input type="text" placeholder="Eg. Formulario" id="buscador">
        <a href="" class="material-icons" id="boton-buscador">search</a>
    </nav>
    <a href="#" class="logo">
        <h1 >DweS</h1>
        <p>Desarrollo web en entorno servidor</p>
    </a>
    <nav class="espacio-hub">
        <a href="https://github.com/MGuiGaDev" class="logo-github" target="_blank" title="Repositorio DWES"><i
                class="fab fa-github"></i></a>
        <a href="https://docs.oracle.com/javaee/7/api/toc.htm" class="logo-java" target="_blank"
           title="API Java 7 EE"><i class="fab fa-java"></i> </a>
        <a  class="logo-java"
            title="C&oacute;mo moverte por el sitio" id="botonInfo" ><i class="fas fa-info-circle"></i></a>
    </nav>
</header>
<nav class="menu">
    <a href="#">Inicio</a>
    <a href="#">Notas</a>
</nav>